# Generated by Django 5.2.12 on 2026-06-26 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('passport_number', models.CharField(max_length=50, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.CharField(blank=True, max_length=50)),
                ('expiry_date', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('image', models.ImageField(blank=True, null=True, upload_to='passport_images/')),
                ('extracted_image', models.ImageField(blank=True, null=True, upload_to='passport_processed/')),
                ('ocr_raw_text', models.TextField(blank=True)),
                ('image_quality_note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('auto-extracted', 'Auto Extracted'), ('manually-corrected', 'Manually Corrected'), ('pending verification', 'Pending Verification')], default='pending verification', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='PassportAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ipv4_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('ipv6_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_attendances', to='events.event')),
                ('passport_visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='passports.passportvisitor')),
            ],
            options={
                'ordering': ['-date', '-time'],
                'constraints': [models.UniqueConstraint(fields=('passport_visitor', 'event'), name='unique_passport_visitor_event_attendance')],
            },
        ),
    ]
