# Generated by Django 5.2.12 on 2026-07-13 00:34

from django.db import migrations, models


def mark_existing_superusers_as_superadmin(apps, schema_editor):
    StaffMember = apps.get_model("staff", "StaffMember")
    StaffMember.objects.filter(user__is_superuser=True).update(role="superadmin")


def restore_superadmin_role_to_admin(apps, schema_editor):
    StaffMember = apps.get_model("staff", "StaffMember")
    StaffMember.objects.filter(role="superadmin").update(role="admin")


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_allow_blank_staff_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
        migrations.RunPython(mark_existing_superusers_as_superadmin, restore_superadmin_role_to_admin),
    ]
