# Generated from ISO 3166 country data used by the frontend passport combobox.
COUNTRY_CODE_MAP = {
    'ABW': 'Aruba',
    'AFG': 'Afghanistan',
    'AGO': 'Angola',
    'AIA': 'Anguilla',
    'ALA': 'Aland Islands',
    'ALB': 'Albania',
    'AND': 'Andorra',
    'ARE': 'United Arab Emirates',
    'ARG': 'Argentina',
    'ARM': 'Armenia',
    'ASM': 'American Samoa',
    'ATA': 'Antarctica',
    'ATF': 'French Southern Territories',
    'ATG': 'Antigua and Barbuda',
    'AUS': 'Australia',
    'AUT': 'Austria',
    'AZE': 'Azerbaijan',
    'BDI': 'Burundi',
    'BEL': 'Belgium',
    'BEN': 'Benin',
    'BES': 'Bonaire, Sint Eustatius and Saba',
    'BFA': 'Burkina Faso',
    'BGD': 'Bangladesh',
    'BGR': 'Bulgaria',
    'BHR': 'Bahrain',
    'BHS': 'Bahamas',
    'BIH': 'Bosnia and Herzegovina',
    'BLM': 'Saint Barthelemy',
    'BLR': 'Belarus',
    'BLZ': 'Belize',
    'BMU': 'Bermuda',
    'BOL': 'Bolivia',
    'BRA': 'Brazil',
    'BRB': 'Barbados',
    'BRN': 'Brunei',
    'BTN': 'Bhutan',
    'BVT': 'Bouvet Island',
    'BWA': 'Botswana',
    'CAF': 'Central African Republic',
    'CAN': 'Canada',
    'CCK': 'Cocos Islands',
    'CHE': 'Switzerland',
    'CHL': 'Chile',
    'CHN': "People's Republic of China",
    'CIV': "Cote d'Ivoire",
    'CMR': 'Cameroon',
    'COD': 'Democratic Republic of the Congo',
    'COG': 'Republic of the Congo',
    'COK': 'Cook Islands',
    'COL': 'Colombia',
    'COM': 'Comoros',
    'CPV': 'Cape Verde',
    'CRI': 'Costa Rica',
    'CUB': 'Cuba',
    'CUW': 'Curacao',
    'CXR': 'Christmas Island',
    'CYM': 'Cayman Islands',
    'CYP': 'Cyprus',
    'CZE': 'Czechia',
    'DEU': 'Germany',
    'DJI': 'Djibouti',
    'DMA': 'Dominica',
    'DNK': 'Denmark',
    'DOM': 'Dominican Republic',
    'DZA': 'Algeria',
    'ECU': 'Ecuador',
    'EGY': 'Egypt',
    'ERI': 'Eritrea',
    'ESH': 'Western Sahara',
    'ESP': 'Spain',
    'EST': 'Estonia',
    'ETH': 'Ethiopia',
    'FIN': 'Finland',
    'FJI': 'Fiji',
    'FLK': 'Falkland Islands',
    'FRA': 'France',
    'FRO': 'Faroe Islands',
    'FSM': 'Micronesia, Federated States of',
    'GAB': 'Gabon',
    'GBR': 'United Kingdom',
    'GEO': 'Georgia',
    'GGY': 'Guernsey',
    'GHA': 'Ghana',
    'GIB': 'Gibraltar',
    'GIN': 'Guinea',
    'GLP': 'Guadeloupe',
    'GMB': 'Republic of The Gambia',
    'GNB': 'Guinea-Bissau',
    'GNQ': 'Equatorial Guinea',
    'GRC': 'Greece',
    'GRD': 'Grenada',
    'GRL': 'Greenland',
    'GTM': 'Guatemala',
    'GUF': 'French Guiana',
    'GUM': 'Guam',
    'GUY': 'Guyana',
    'HKG': 'Hong Kong',
    'HMD': 'Heard Island and McDonald Islands',
    'HND': 'Honduras',
    'HRV': 'Croatia',
    'HTI': 'Haiti',
    'HUN': 'Hungary',
    'IDN': 'Indonesia',
    'IMN': 'Isle of Man',
    'IND': 'India',
    'IOT': 'British Indian Ocean Territory',
    'IRL': 'Ireland',
    'IRN': 'Iran',
    'IRQ': 'Iraq',
    'ISL': 'Iceland',
    'ISR': 'Israel',
    'ITA': 'Italy',
    'JAM': 'Jamaica',
    'JEY': 'Jersey',
    'JOR': 'Jordan',
    'JPN': 'Japan',
    'KAZ': 'Kazakhstan',
    'KEN': 'Kenya',
    'KGZ': 'Kyrgyzstan',
    'KHM': 'Cambodia',
    'KIR': 'Kiribati',
    'KNA': 'Saint Kitts and Nevis',
    'KOR': 'South Korea',
    'KWT': 'Kuwait',
    'LAO': 'Laos',
    'LBN': 'Lebanon',
    'LBR': 'Liberia',
    'LBY': 'Libya',
    'LCA': 'Saint Lucia',
    'LIE': 'Liechtenstein',
    'LKA': 'Sri Lanka',
    'LSO': 'Lesotho',
    'LTU': 'Lithuania',
    'LUX': 'Luxembourg',
    'LVA': 'Latvia',
    'MAC': 'Macao',
    'MAF': 'Saint Martin (French part)',
    'MAR': 'Morocco',
    'MCO': 'Monaco',
    'MDA': 'Moldova',
    'MDG': 'Madagascar',
    'MDV': 'Maldives',
    'MEX': 'Mexico',
    'MHL': 'Marshall Islands',
    'MKD': 'The Republic of North Macedonia',
    'MLI': 'Mali',
    'MLT': 'Malta',
    'MMR': 'Myanmar',
    'MNE': 'Montenegro',
    'MNG': 'Mongolia',
    'MNP': 'Northern Mariana Islands',
    'MOZ': 'Mozambique',
    'MRT': 'Mauritania',
    'MSR': 'Montserrat',
    'MTQ': 'Martinique',
    'MUS': 'Mauritius',
    'MWI': 'Malawi',
    'MYS': 'Malaysia',
    'MYT': 'Mayotte',
    'NAM': 'Namibia',
    'NCL': 'New Caledonia',
    'NER': 'Niger',
    'NFK': 'Norfolk Island',
    'NGA': 'Nigeria',
    'NIC': 'Nicaragua',
    'NIU': 'Niue',
    'NLD': 'Netherlands',
    'NOR': 'Norway',
    'NPL': 'Nepal',
    'NRU': 'Nauru',
    'NZL': 'New Zealand',
    'OMN': 'Oman',
    'PAK': 'Pakistan',
    'PAN': 'Panama',
    'PCN': 'Pitcairn',
    'PER': 'Peru',
    'PHL': 'Philippines',
    'PLW': 'Palau',
    'PNG': 'Papua New Guinea',
    'POL': 'Poland',
    'PRI': 'Puerto Rico',
    'PRK': 'North Korea',
    'PRT': 'Portugal',
    'PRY': 'Paraguay',
    'PSE': 'Palestine',
    'PYF': 'French Polynesia',
    'QAT': 'Qatar',
    'REU': 'Reunion',
    'ROU': 'Romania',
    'RUS': 'Russia',
    'RWA': 'Rwanda',
    'SAU': 'Saudi Arabia',
    'SDN': 'Sudan',
    'SEN': 'Senegal',
    'SGP': 'Singapore',
    'SGS': 'South Georgia and the South Sandwich Islands',
    'SHN': 'Saint Helena',
    'SJM': 'Svalbard and Jan Mayen',
    'SLB': 'Solomon Islands',
    'SLE': 'Sierra Leone',
    'SLV': 'El Salvador',
    'SMR': 'San Marino',
    'SOM': 'Somalia',
    'SPM': 'Saint Pierre and Miquelon',
    'SRB': 'Serbia',
    'SSD': 'South Sudan',
    'STP': 'Sao Tome and Principe',
    'SUR': 'Suriname',
    'SVK': 'Slovakia',
    'SVN': 'Slovenia',
    'SWE': 'Sweden',
    'SWZ': 'Eswatini',
    'SXM': 'Sint Maarten (Dutch part)',
    'SYC': 'Seychelles',
    'SYR': 'Syria',
    'TCA': 'Turks and Caicos Islands',
    'TCD': 'Chad',
    'TGO': 'Togo',
    'THA': 'Thailand',
    'TJK': 'Tajikistan',
    'TKL': 'Tokelau',
    'TKM': 'Turkmenistan',
    'TLS': 'Timor-Leste',
    'TON': 'Tonga',
    'TTO': 'Trinidad and Tobago',
    'TUN': 'Tunisia',
    'TUR': 'Turkiye',
    'TUV': 'Tuvalu',
    'TWN': 'Taiwan',
    'TZA': 'Tanzania',
    'UGA': 'Uganda',
    'UKR': 'Ukraine',
    'UMI': 'United States Minor Outlying Islands',
    'URY': 'Uruguay',
    'USA': 'United States',
    'UZB': 'Uzbekistan',
    'VAT': 'Holy See (Vatican City State)',
    'VCT': 'Saint Vincent and the Grenadines',
    'VEN': 'Venezuela',
    'VGB': 'British Virgin Islands',
    'VIR': 'U.S. Virgin Islands',
    'VNM': 'Vietnam',
    'VUT': 'Vanuatu',
    'WLF': 'Wallis and Futuna',
    'WSM': 'Samoa',
    'XKK': 'Kosovo',
    'XKX': 'Kosovo',
    'YEM': 'Yemen',
    'ZAF': 'South Africa',
    'ZMB': 'Zambia',
    'ZWE': 'Zimbabwe',
}

COUNTRY_NAME_CODE_MAP = {
    'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS': 'SGS',
    'UNITED STATES MINOR OUTLYING ISLANDS': 'UMI',
    'HEARD ISLAND AND MCDONALD ISLANDS': 'HMD',
    'BONAIRE, SINT EUSTATIUS AND SABA': 'BES',
    'DEMOCRATIC REPUBLIC OF THE CONGO': 'COD',
    "LAO PEOPLE'S DEMOCRATIC REPUBLIC": 'LAO',
    'SAINT VINCENT AND THE GRENADINES': 'VCT',
    'MICRONESIA, FEDERATED STATES OF': 'FSM',
    'THE REPUBLIC OF NORTH MACEDONIA': 'MKD',
    'BRITISH INDIAN OCEAN TERRITORY': 'IOT',
    'HOLY SEE (VATICAN CITY STATE)': 'VAT',
    'NETHERLANDS (KINGDOM OF THE)': 'NLD',
    'FALKLAND ISLANDS (MALVINAS)': 'FLK',
    'FRENCH SOUTHERN TERRITORIES': 'ATF',
    'UNITED REPUBLIC OF TANZANIA': 'TZA',
    "PEOPLE'S REPUBLIC OF CHINA": 'CHN',
    'SAINT MARTIN (FRENCH PART)': 'MAF',
    'SAINT PIERRE AND MIQUELON': 'SPM',
    'SINT MAARTEN (DUTCH PART)': 'SXM',
    'TAIWAN, PROVINCE OF CHINA': 'TWN',
    'CENTRAL AFRICAN REPUBLIC': 'CAF',
    'ISLAMIC REPUBLIC OF IRAN': 'IRN',
    'NORTHERN MARIANA ISLANDS': 'MNP',
    'TURKS AND CAICOS ISLANDS': 'TCA',
    'UNITED STATES OF AMERICA': 'USA',
    'COCOS (KEELING) ISLANDS': 'CCK',
    'VIRGIN ISLANDS, BRITISH': 'VGB',
    'BOSNIA AND HERZEGOVINA': 'BIH',
    'BRITISH VIRGIN ISLANDS': 'VGB',
    'REPUBLIC OF THE GAMBIA': 'GMB',
    'SVALBARD AND JAN MAYEN': 'SJM',
    'REPUBLIC OF THE CONGO': 'COG',
    'SAINT KITTS AND NEVIS': 'KNA',
    'SAO TOME AND PRINCIPE': 'STP',
    'MOLDOVA, REPUBLIC OF': 'MDA',
    'SYRIAN ARAB REPUBLIC': 'SYR',
    'UNITED ARAB EMIRATES': 'ARE',
    'VIRGIN ISLANDS, U.S.': 'VIR',
    'ANTIGUA AND BARBUDA': 'ATG',
    'TRINIDAD AND TOBAGO': 'TTO',
    'U.S. VIRGIN ISLANDS': 'VIR',
    'DOMINICAN REPUBLIC': 'DOM',
    'KOREA, REPUBLIC OF': 'KOR',
    'REPUBLIC OF KOSOVO': 'XKX',
    'RUSSIAN FEDERATION': 'RUS',
    'STATE OF PALESTINE': 'PSE',
    'BRUNEI DARUSSALAM': 'BRN',
    'EQUATORIAL GUINEA': 'GNQ',
    'REPUBLIC OF KOREA': 'KOR',
    'WALLIS AND FUTUNA': 'WLF',
    'CHRISTMAS ISLAND': 'CXR',
    'FALKLAND ISLANDS': 'FLK',
    'FRENCH POLYNESIA': 'PYF',
    'MARSHALL ISLANDS': 'MHL',
    'PAPUA NEW GUINEA': 'PNG',
    'PITCAIRN ISLANDS': 'PCN',
    'SAINT BARTHELEMY': 'BLM',
    'NORTH MACEDONIA': 'MKD',
    'SOLOMON ISLANDS': 'SLB',
    'THE NETHERLANDS': 'NLD',
    'AMERICAN SAMOA': 'ASM',
    'CAYMAN ISLANDS': 'CYM',
    'CZECH REPUBLIC': 'CZE',
    'NORFOLK ISLAND': 'NFK',
    'UNITED KINGDOM': 'GBR',
    'WESTERN SAHARA': 'ESH',
    'ALAND ISLANDS': 'ALA',
    'BOUVET ISLAND': 'BVT',
    'COCOS ISLANDS': 'CCK',
    "COTE D'IVOIRE": 'CIV',
    'FAROE ISLANDS': 'FRO',
    'FRENCH GUIANA': 'GUF',
    'GREAT BRITAIN': 'GBR',
    'GUINEA-BISSAU': 'GNB',
    'LIECHTENSTEIN': 'LIE',
    'NEW CALEDONIA': 'NCL',
    'UNITED STATES': 'USA',
    'BURKINA FASO': 'BFA',
    'COOK ISLANDS': 'COK',
    'SAINT HELENA': 'SHN',
    'SAUDI ARABIA': 'SAU',
    'SIERRA LEONE': 'SLE',
    'SOUTH AFRICA': 'ZAF',
    'TURKMENISTAN': 'TKM',
    'VATICAN CITY': 'VAT',
    'AFGHANISTAN': 'AFG',
    'EL SALVADOR': 'SLV',
    'ISLE OF MAN': 'IMN',
    'IVORY COAST': 'CIV',
    'NETHERLANDS': 'NLD',
    'NEW ZEALAND': 'NZL',
    'NORTH KOREA': 'PRK',
    'PHILIPPINES': 'PHL',
    'PUERTO RICO': 'PRI',
    'SAINT LUCIA': 'LCA',
    'SOUTH KOREA': 'KOR',
    'SOUTH SUDAN': 'SSD',
    'SWITZERLAND': 'CHE',
    'TIMOR-LESTE': 'TLS',
    'ANTARCTICA': 'ATA',
    'AZERBAIJAN': 'AZE',
    'BANGLADESH': 'BGD',
    'CAPE VERDE': 'CPV',
    'COSTA RICA': 'CRI',
    'GUADELOUPE': 'GLP',
    'KAZAKHSTAN': 'KAZ',
    'KYRGYZSTAN': 'KGZ',
    'LUXEMBOURG': 'LUX',
    'MADAGASCAR': 'MDG',
    'MARTINIQUE': 'MTQ',
    'MAURITANIA': 'MRT',
    'MONTENEGRO': 'MNE',
    'MONTSERRAT': 'MSR',
    'MOZAMBIQUE': 'MOZ',
    'SAN MARINO': 'SMR',
    'SEYCHELLES': 'SYC',
    'TAJIKISTAN': 'TJK',
    'THE GAMBIA': 'GMB',
    'UZBEKISTAN': 'UZB',
    'ARGENTINA': 'ARG',
    'AUSTRALIA': 'AUS',
    'GIBRALTAR': 'GIB',
    'GREENLAND': 'GRL',
    'GUATEMALA': 'GTM',
    'HONG KONG': 'HKG',
    'INDONESIA': 'IDN',
    'LITHUANIA': 'LTU',
    'MAURITIUS': 'MUS',
    'NICARAGUA': 'NIC',
    'PALESTINE': 'PSE',
    'SINGAPORE': 'SGP',
    'SRI LANKA': 'LKA',
    'VENEZUELA': 'VEN',
    'ANGUILLA': 'AIA',
    'BARBADOS': 'BRB',
    'BOTSWANA': 'BWA',
    'BULGARIA': 'BGR',
    'CAMBODIA': 'KHM',
    'CAMEROON': 'CMR',
    'COLOMBIA': 'COL',
    'DJIBOUTI': 'DJI',
    'DOMINICA': 'DMA',
    'ESWATINI': 'SWZ',
    'ETHIOPIA': 'ETH',
    'GUERNSEY': 'GGY',
    'HOLY SEE': 'VAT',
    'HONDURAS': 'HND',
    'KIRIBATI': 'KIR',
    'MALAYSIA': 'MYS',
    'MALDIVES': 'MDV',
    'MONGOLIA': 'MNG',
    'PAKISTAN': 'PAK',
    'PARAGUAY': 'PRY',
    'PITCAIRN': 'PCN',
    'PORTUGAL': 'PRT',
    'SLOVAKIA': 'SVK',
    'SLOVENIA': 'SVN',
    'SURINAME': 'SUR',
    'TANZANIA': 'TZA',
    'THAILAND': 'THA',
    'ZIMBABWE': 'ZWE',
    'ALBANIA': 'ALB',
    'ALGERIA': 'DZA',
    'ANDORRA': 'AND',
    'ARMENIA': 'ARM',
    'AUSTRIA': 'AUT',
    'BAHAMAS': 'BHS',
    'BAHRAIN': 'BHR',
    'BELARUS': 'BLR',
    'BELGIUM': 'BEL',
    'BERMUDA': 'BMU',
    'BOLIVIA': 'BOL',
    'BRITAIN': 'GBR',
    'BURUNDI': 'BDI',
    'COMOROS': 'COM',
    'CROATIA': 'HRV',
    'CURACAO': 'CUW',
    'CZECHIA': 'CZE',
    'DENMARK': 'DNK',
    'ECUADOR': 'ECU',
    'ERITREA': 'ERI',
    'ESTONIA': 'EST',
    'FINLAND': 'FIN',
    'GEORGIA': 'GEO',
    'GERMANY': 'DEU',
    'GRENADA': 'GRD',
    'HUNGARY': 'HUN',
    'ICELAND': 'ISL',
    'IRELAND': 'IRL',
    'JAMAICA': 'JAM',
    'LEBANON': 'LBN',
    'LESOTHO': 'LSO',
    'LIBERIA': 'LBR',
    'MAYOTTE': 'MYT',
    'MOLDOVA': 'MDA',
    'MOROCCO': 'MAR',
    'MYANMAR': 'MMR',
    'NAMIBIA': 'NAM',
    'NIGERIA': 'NGA',
    'REUNION': 'REU',
    'ROMANIA': 'ROU',
    'SENEGAL': 'SEN',
    'SOMALIA': 'SOM',
    'TOKELAU': 'TKL',
    'TUNISIA': 'TUN',
    'TURKIYE': 'TUR',
    'UKRAINE': 'UKR',
    'URUGUAY': 'URY',
    'VANUATU': 'VUT',
    'VIETNAM': 'VNM',
    'ANGOLA': 'AGO',
    'BELIZE': 'BLZ',
    'BHUTAN': 'BTN',
    'BRAZIL': 'BRA',
    'BRUNEI': 'BRN',
    'CANADA': 'CAN',
    'CYPRUS': 'CYP',
    'FRANCE': 'FRA',
    'GAMBIA': 'GMB',
    'GREECE': 'GRC',
    'GUINEA': 'GIN',
    'GUYANA': 'GUY',
    'ISRAEL': 'ISR',
    'JERSEY': 'JEY',
    'JORDAN': 'JOR',
    'KOSOVO': 'XKK',
    'KUWAIT': 'KWT',
    'LATVIA': 'LVA',
    'MALAWI': 'MWI',
    'MEXICO': 'MEX',
    'MONACO': 'MCO',
    'NORWAY': 'NOR',
    'PANAMA': 'PAN',
    'POLAND': 'POL',
    'RUSSIA': 'RUS',
    'RWANDA': 'RWA',
    'SERBIA': 'SRB',
    'SWEDEN': 'SWE',
    'TAIWAN': 'TWN',
    'TURKEY': 'TUR',
    'TUVALU': 'TUV',
    'U.S.A.': 'USA',
    'UGANDA': 'UGA',
    'ZAMBIA': 'ZMB',
    'ARUBA': 'ABW',
    'BENIN': 'BEN',
    'CHILE': 'CHL',
    'CHINA': 'CHN',
    'CONGO': 'COD',
    'EGYPT': 'EGY',
    'GABON': 'GAB',
    'GHANA': 'GHA',
    'HAITI': 'HTI',
    'INDIA': 'IND',
    'ITALY': 'ITA',
    'JAPAN': 'JPN',
    'KENYA': 'KEN',
    'KOREA': 'KOR',
    'LIBYA': 'LBY',
    'MACAO': 'MAC',
    'MALTA': 'MLT',
    'NAURU': 'NRU',
    'NEPAL': 'NPL',
    'NIGER': 'NER',
    'PALAU': 'PLW',
    'QATAR': 'QAT',
    'SAMOA': 'WSM',
    'SPAIN': 'ESP',
    'SUDAN': 'SDN',
    'SYRIA': 'SYR',
    'TONGA': 'TON',
    'YEMEN': 'YEM',
    'CHAD': 'TCD',
    'CUBA': 'CUB',
    'DPRK': 'PRK',
    'FIJI': 'FJI',
    'GUAM': 'GUM',
    'IRAN': 'IRN',
    'IRAQ': 'IRQ',
    'LAOS': 'LAO',
    'MALI': 'MLI',
    'NIUE': 'NIU',
    'OMAN': 'OMN',
    'PERU': 'PER',
    'TOGO': 'TGO',
    'UAE': 'ARE',
    'USA': 'USA',
}

