export const passportCountryOptions = [
  { code: "AFG", nationality: "Afghanistan", aliases: [] },
  { code: "ALA", nationality: "Aland Islands", aliases: [] },
  { code: "ALB", nationality: "Albania", aliases: [] },
  { code: "DZA", nationality: "Algeria", aliases: [] },
  { code: "ASM", nationality: "American Samoa", aliases: [] },
  { code: "AND", nationality: "Andorra", aliases: [] },
  { code: "AGO", nationality: "Angola", aliases: [] },
  { code: "AIA", nationality: "Anguilla", aliases: [] },
  { code: "ATA", nationality: "Antarctica", aliases: [] },
  { code: "ATG", nationality: "Antigua and Barbuda", aliases: [] },
  { code: "ARG", nationality: "Argentina", aliases: [] },
  { code: "ARM", nationality: "Armenia", aliases: [] },
  { code: "ABW", nationality: "Aruba", aliases: [] },
  { code: "AUS", nationality: "Australia", aliases: [] },
  { code: "AUT", nationality: "Austria", aliases: [] },
  { code: "AZE", nationality: "Azerbaijan", aliases: [] },
  { code: "BHS", nationality: "Bahamas", aliases: [] },
  { code: "BHR", nationality: "Bahrain", aliases: [] },
  { code: "BGD", nationality: "Bangladesh", aliases: [] },
  { code: "BRB", nationality: "Barbados", aliases: [] },
  { code: "BLR", nationality: "Belarus", aliases: [] },
  { code: "BEL", nationality: "Belgium", aliases: [] },
  { code: "BLZ", nationality: "Belize", aliases: [] },
  { code: "BEN", nationality: "Benin", aliases: [] },
  { code: "BMU", nationality: "Bermuda", aliases: [] },
  { code: "BTN", nationality: "Bhutan", aliases: [] },
  { code: "BOL", nationality: "Bolivia", aliases: [] },
  { code: "BES", nationality: "Bonaire, Sint Eustatius and Saba", aliases: [] },
  { code: "BIH", nationality: "Bosnia and Herzegovina", aliases: [] },
  { code: "BWA", nationality: "Botswana", aliases: [] },
  { code: "BVT", nationality: "Bouvet Island", aliases: [] },
  { code: "BRA", nationality: "Brazil", aliases: [] },
  { code: "IOT", nationality: "British Indian Ocean Territory", aliases: [] },
  { code: "VGB", nationality: "British Virgin Islands", aliases: ["Virgin Islands, British"] },
  { code: "BRN", nationality: "Brunei", aliases: ["Brunei Darussalam"] },
  { code: "BGR", nationality: "Bulgaria", aliases: [] },
  { code: "BFA", nationality: "Burkina Faso", aliases: [] },
  { code: "BDI", nationality: "Burundi", aliases: [] },
  { code: "KHM", nationality: "Cambodia", aliases: [] },
  { code: "CMR", nationality: "Cameroon", aliases: [] },
  { code: "CAN", nationality: "Canada", aliases: [] },
  { code: "CPV", nationality: "Cape Verde", aliases: [] },
  { code: "CYM", nationality: "Cayman Islands", aliases: [] },
  { code: "CAF", nationality: "Central African Republic", aliases: [] },
  { code: "TCD", nationality: "Chad", aliases: [] },
  { code: "CHL", nationality: "Chile", aliases: [] },
  { code: "CXR", nationality: "Christmas Island", aliases: [] },
  { code: "CCK", nationality: "Cocos Islands", aliases: ["Cocos (Keeling) Islands"] },
  { code: "COL", nationality: "Colombia", aliases: [] },
  { code: "COM", nationality: "Comoros", aliases: [] },
  { code: "COK", nationality: "Cook Islands", aliases: [] },
  { code: "CRI", nationality: "Costa Rica", aliases: [] },
  { code: "CIV", nationality: "Cote d'Ivoire", aliases: ["Ivory Coast"] },
  { code: "HRV", nationality: "Croatia", aliases: [] },
  { code: "CUB", nationality: "Cuba", aliases: [] },
  { code: "CUW", nationality: "Curacao", aliases: [] },
  { code: "CYP", nationality: "Cyprus", aliases: [] },
  { code: "CZE", nationality: "Czechia", aliases: ["Czech Republic"] },
  { code: "COD", nationality: "Democratic Republic of the Congo", aliases: ["Congo"] },
  { code: "DNK", nationality: "Denmark", aliases: [] },
  { code: "DJI", nationality: "Djibouti", aliases: [] },
  { code: "DMA", nationality: "Dominica", aliases: [] },
  { code: "DOM", nationality: "Dominican Republic", aliases: [] },
  { code: "ECU", nationality: "Ecuador", aliases: [] },
  { code: "EGY", nationality: "Egypt", aliases: [] },
  { code: "SLV", nationality: "El Salvador", aliases: [] },
  { code: "GNQ", nationality: "Equatorial Guinea", aliases: [] },
  { code: "ERI", nationality: "Eritrea", aliases: [] },
  { code: "EST", nationality: "Estonia", aliases: [] },
  { code: "SWZ", nationality: "Eswatini", aliases: [] },
  { code: "ETH", nationality: "Ethiopia", aliases: [] },
  { code: "FLK", nationality: "Falkland Islands", aliases: ["Falkland Islands (Malvinas)"] },
  { code: "FRO", nationality: "Faroe Islands", aliases: [] },
  { code: "FJI", nationality: "Fiji", aliases: [] },
  { code: "FIN", nationality: "Finland", aliases: [] },
  { code: "FRA", nationality: "France", aliases: [] },
  { code: "GUF", nationality: "French Guiana", aliases: [] },
  { code: "PYF", nationality: "French Polynesia", aliases: [] },
  { code: "ATF", nationality: "French Southern Territories", aliases: [] },
  { code: "GAB", nationality: "Gabon", aliases: [] },
  { code: "GEO", nationality: "Georgia", aliases: [] },
  { code: "DEU", nationality: "Germany", aliases: [] },
  { code: "GHA", nationality: "Ghana", aliases: [] },
  { code: "GIB", nationality: "Gibraltar", aliases: [] },
  { code: "GRC", nationality: "Greece", aliases: [] },
  { code: "GRL", nationality: "Greenland", aliases: [] },
  { code: "GRD", nationality: "Grenada", aliases: [] },
  { code: "GLP", nationality: "Guadeloupe", aliases: [] },
  { code: "GUM", nationality: "Guam", aliases: [] },
  { code: "GTM", nationality: "Guatemala", aliases: [] },
  { code: "GGY", nationality: "Guernsey", aliases: [] },
  { code: "GIN", nationality: "Guinea", aliases: [] },
  { code: "GNB", nationality: "Guinea-Bissau", aliases: [] },
  { code: "GUY", nationality: "Guyana", aliases: [] },
  { code: "HTI", nationality: "Haiti", aliases: [] },
  { code: "HMD", nationality: "Heard Island and McDonald Islands", aliases: [] },
  { code: "VAT", nationality: "Holy See (Vatican City State)", aliases: ["Vatican City", "Holy See"] },
  { code: "HND", nationality: "Honduras", aliases: [] },
  { code: "HKG", nationality: "Hong Kong", aliases: [] },
  { code: "HUN", nationality: "Hungary", aliases: [] },
  { code: "ISL", nationality: "Iceland", aliases: [] },
  { code: "IND", nationality: "India", aliases: [] },
  { code: "IDN", nationality: "Indonesia", aliases: [] },
  { code: "IRN", nationality: "Iran", aliases: ["Islamic Republic of Iran"] },
  { code: "IRQ", nationality: "Iraq", aliases: [] },
  { code: "IRL", nationality: "Ireland", aliases: [] },
  { code: "IMN", nationality: "Isle of Man", aliases: [] },
  { code: "ISR", nationality: "Israel", aliases: [] },
  { code: "ITA", nationality: "Italy", aliases: [] },
  { code: "JAM", nationality: "Jamaica", aliases: [] },
  { code: "JPN", nationality: "Japan", aliases: [] },
  { code: "JEY", nationality: "Jersey", aliases: [] },
  { code: "JOR", nationality: "Jordan", aliases: [] },
  { code: "KAZ", nationality: "Kazakhstan", aliases: [] },
  { code: "KEN", nationality: "Kenya", aliases: [] },
  { code: "KIR", nationality: "Kiribati", aliases: [] },
  { code: "XKK", nationality: "Kosovo", aliases: [] },
  { code: "XKX", nationality: "Kosovo", aliases: ["Republic of Kosovo"] },
  { code: "KWT", nationality: "Kuwait", aliases: [] },
  { code: "KGZ", nationality: "Kyrgyzstan", aliases: [] },
  { code: "LAO", nationality: "Laos", aliases: ["Lao People's Democratic Republic"] },
  { code: "LVA", nationality: "Latvia", aliases: [] },
  { code: "LBN", nationality: "Lebanon", aliases: [] },
  { code: "LSO", nationality: "Lesotho", aliases: [] },
  { code: "LBR", nationality: "Liberia", aliases: [] },
  { code: "LBY", nationality: "Libya", aliases: [] },
  { code: "LIE", nationality: "Liechtenstein", aliases: [] },
  { code: "LTU", nationality: "Lithuania", aliases: [] },
  { code: "LUX", nationality: "Luxembourg", aliases: [] },
  { code: "MAC", nationality: "Macao", aliases: [] },
  { code: "MDG", nationality: "Madagascar", aliases: [] },
  { code: "MWI", nationality: "Malawi", aliases: [] },
  { code: "MYS", nationality: "Malaysia", aliases: [] },
  { code: "MDV", nationality: "Maldives", aliases: [] },
  { code: "MLI", nationality: "Mali", aliases: [] },
  { code: "MLT", nationality: "Malta", aliases: [] },
  { code: "MHL", nationality: "Marshall Islands", aliases: [] },
  { code: "MTQ", nationality: "Martinique", aliases: [] },
  { code: "MRT", nationality: "Mauritania", aliases: [] },
  { code: "MUS", nationality: "Mauritius", aliases: [] },
  { code: "MYT", nationality: "Mayotte", aliases: [] },
  { code: "MEX", nationality: "Mexico", aliases: [] },
  { code: "FSM", nationality: "Micronesia, Federated States of", aliases: [] },
  { code: "MDA", nationality: "Moldova", aliases: ["Moldova, Republic of"] },
  { code: "MCO", nationality: "Monaco", aliases: [] },
  { code: "MNG", nationality: "Mongolia", aliases: [] },
  { code: "MNE", nationality: "Montenegro", aliases: [] },
  { code: "MSR", nationality: "Montserrat", aliases: [] },
  { code: "MAR", nationality: "Morocco", aliases: [] },
  { code: "MOZ", nationality: "Mozambique", aliases: [] },
  { code: "MMR", nationality: "Myanmar", aliases: [] },
  { code: "NAM", nationality: "Namibia", aliases: [] },
  { code: "NRU", nationality: "Nauru", aliases: [] },
  { code: "NPL", nationality: "Nepal", aliases: [] },
  { code: "NLD", nationality: "Netherlands", aliases: ["The Netherlands", "Netherlands (Kingdom of the)"] },
  { code: "NCL", nationality: "New Caledonia", aliases: [] },
  { code: "NZL", nationality: "New Zealand", aliases: [] },
  { code: "NIC", nationality: "Nicaragua", aliases: [] },
  { code: "NER", nationality: "Niger", aliases: [] },
  { code: "NGA", nationality: "Nigeria", aliases: [] },
  { code: "NIU", nationality: "Niue", aliases: [] },
  { code: "NFK", nationality: "Norfolk Island", aliases: [] },
  { code: "PRK", nationality: "North Korea", aliases: ["DPRK"] },
  { code: "MNP", nationality: "Northern Mariana Islands", aliases: [] },
  { code: "NOR", nationality: "Norway", aliases: [] },
  { code: "OMN", nationality: "Oman", aliases: [] },
  { code: "PAK", nationality: "Pakistan", aliases: [] },
  { code: "PLW", nationality: "Palau", aliases: [] },
  { code: "PSE", nationality: "Palestine", aliases: ["State of Palestine"] },
  { code: "PAN", nationality: "Panama", aliases: [] },
  { code: "PNG", nationality: "Papua New Guinea", aliases: [] },
  { code: "PRY", nationality: "Paraguay", aliases: [] },
  { code: "CHN", nationality: "People's Republic of China", aliases: ["China"] },
  { code: "PER", nationality: "Peru", aliases: [] },
  { code: "PHL", nationality: "Philippines", aliases: [] },
  { code: "PCN", nationality: "Pitcairn", aliases: ["Pitcairn Islands"] },
  { code: "POL", nationality: "Poland", aliases: [] },
  { code: "PRT", nationality: "Portugal", aliases: [] },
  { code: "PRI", nationality: "Puerto Rico", aliases: [] },
  { code: "QAT", nationality: "Qatar", aliases: [] },
  { code: "GMB", nationality: "Republic of The Gambia", aliases: ["The Gambia", "Gambia"] },
  { code: "COG", nationality: "Republic of the Congo", aliases: ["Congo"] },
  { code: "REU", nationality: "Reunion", aliases: [] },
  { code: "ROU", nationality: "Romania", aliases: [] },
  { code: "RUS", nationality: "Russia", aliases: ["Russian Federation"] },
  { code: "RWA", nationality: "Rwanda", aliases: [] },
  { code: "BLM", nationality: "Saint Barthelemy", aliases: [] },
  { code: "SHN", nationality: "Saint Helena", aliases: [] },
  { code: "KNA", nationality: "Saint Kitts and Nevis", aliases: [] },
  { code: "LCA", nationality: "Saint Lucia", aliases: [] },
  { code: "MAF", nationality: "Saint Martin (French part)", aliases: [] },
  { code: "SPM", nationality: "Saint Pierre and Miquelon", aliases: [] },
  { code: "VCT", nationality: "Saint Vincent and the Grenadines", aliases: [] },
  { code: "WSM", nationality: "Samoa", aliases: [] },
  { code: "SMR", nationality: "San Marino", aliases: [] },
  { code: "STP", nationality: "Sao Tome and Principe", aliases: [] },
  { code: "SAU", nationality: "Saudi Arabia", aliases: [] },
  { code: "SEN", nationality: "Senegal", aliases: [] },
  { code: "SRB", nationality: "Serbia", aliases: [] },
  { code: "SYC", nationality: "Seychelles", aliases: [] },
  { code: "SLE", nationality: "Sierra Leone", aliases: [] },
  { code: "SGP", nationality: "Singapore", aliases: [] },
  { code: "SXM", nationality: "Sint Maarten (Dutch part)", aliases: [] },
  { code: "SVK", nationality: "Slovakia", aliases: [] },
  { code: "SVN", nationality: "Slovenia", aliases: [] },
  { code: "SLB", nationality: "Solomon Islands", aliases: [] },
  { code: "SOM", nationality: "Somalia", aliases: [] },
  { code: "ZAF", nationality: "South Africa", aliases: [] },
  { code: "SGS", nationality: "South Georgia and the South Sandwich Islands", aliases: [] },
  { code: "KOR", nationality: "South Korea", aliases: ["Korea, Republic of", "Republic of Korea", "Korea"] },
  { code: "SSD", nationality: "South Sudan", aliases: [] },
  { code: "ESP", nationality: "Spain", aliases: [] },
  { code: "LKA", nationality: "Sri Lanka", aliases: [] },
  { code: "SDN", nationality: "Sudan", aliases: [] },
  { code: "SUR", nationality: "Suriname", aliases: [] },
  { code: "SJM", nationality: "Svalbard and Jan Mayen", aliases: [] },
  { code: "SWE", nationality: "Sweden", aliases: [] },
  { code: "CHE", nationality: "Switzerland", aliases: [] },
  { code: "SYR", nationality: "Syria", aliases: ["Syrian Arab Republic"] },
  { code: "TWN", nationality: "Taiwan", aliases: ["Taiwan, Province of China"] },
  { code: "TJK", nationality: "Tajikistan", aliases: [] },
  { code: "TZA", nationality: "Tanzania", aliases: ["United Republic of Tanzania"] },
  { code: "THA", nationality: "Thailand", aliases: [] },
  { code: "MKD", nationality: "The Republic of North Macedonia", aliases: ["North Macedonia"] },
  { code: "TLS", nationality: "Timor-Leste", aliases: [] },
  { code: "TGO", nationality: "Togo", aliases: [] },
  { code: "TKL", nationality: "Tokelau", aliases: [] },
  { code: "TON", nationality: "Tonga", aliases: [] },
  { code: "TTO", nationality: "Trinidad and Tobago", aliases: [] },
  { code: "TUN", nationality: "Tunisia", aliases: [] },
  { code: "TUR", nationality: "Turkiye", aliases: ["Turkey"] },
  { code: "TKM", nationality: "Turkmenistan", aliases: [] },
  { code: "TCA", nationality: "Turks and Caicos Islands", aliases: [] },
  { code: "TUV", nationality: "Tuvalu", aliases: [] },
  { code: "VIR", nationality: "U.S. Virgin Islands", aliases: ["Virgin Islands, U.S."] },
  { code: "UGA", nationality: "Uganda", aliases: [] },
  { code: "UKR", nationality: "Ukraine", aliases: [] },
  { code: "ARE", nationality: "United Arab Emirates", aliases: ["UAE"] },
  { code: "GBR", nationality: "United Kingdom", aliases: ["UK", "Great Britain", "Britain"] },
  { code: "USA", nationality: "United States", aliases: ["United States of America", "USA", "U.S.A.", "US", "U.S."] },
  { code: "UMI", nationality: "United States Minor Outlying Islands", aliases: [] },
  { code: "URY", nationality: "Uruguay", aliases: [] },
  { code: "UZB", nationality: "Uzbekistan", aliases: [] },
  { code: "VUT", nationality: "Vanuatu", aliases: [] },
  { code: "VEN", nationality: "Venezuela", aliases: [] },
  { code: "VNM", nationality: "Vietnam", aliases: [] },
  { code: "WLF", nationality: "Wallis and Futuna", aliases: [] },
  { code: "ESH", nationality: "Western Sahara", aliases: [] },
  { code: "YEM", nationality: "Yemen", aliases: [] },
  { code: "ZMB", nationality: "Zambia", aliases: [] },
  { code: "ZWE", nationality: "Zimbabwe", aliases: [] },
]

export function normalisePassportCountryText(value) {
  return String(value || '').trim().toLowerCase()
}

export function findPassportCountryByCode(value) {
  const code = String(value || '').trim().toUpperCase()
  return passportCountryOptions.find((option) => option.code === code)
}

export function findPassportCountryByNationality(value) {
  const nationality = normalisePassportCountryText(value)
  return passportCountryOptions.find((option) => (
    normalisePassportCountryText(option.nationality) === nationality
    || option.aliases.some((alias) => normalisePassportCountryText(alias) === nationality)
  ))
}

export function filterPassportCountries(query) {
  const search = normalisePassportCountryText(query)
  if (!search) return passportCountryOptions.slice(0, 24)
  return passportCountryOptions.filter((option) => {
    const values = [option.code, option.nationality, ...option.aliases]
    return values.some((value) => normalisePassportCountryText(value).includes(search))
  }).slice(0, 40)
}
